version: 0.2

phases:
  install:
    commands:
      - apt-get install curl -y
      - curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - apt-get clean
      - apt-get install nodejs npm
      - echo Entered the install phase...
      - npm init -yy
      - npm i --save @11ty/eleventy
      - npm i --save js-yaml 
    finally:
      - echo Installation done
  build:
    commands:
      - echo Entered the build phase ...
      - npm run build
    finally:
      - echo Building the HTML files finished
  post_build:
    commands:
      - echo Current directory is $CODEBUILD_SRC_DIR
      - ls -la
artifacts:
  files:
    - '**/*'
  base-directory: dist
